### PR TITLE
UDT Types

### PR DESCRIPTION
**Pull request by UnbounDev**
@rashtao starting the PR up so we can easily view the code diff, please keep the same format when making edits (two space hard indents - no soft tabs) - else the diff is hard to visually parse.

### CODE REVIEW

**Comment by UnbounDev** [comment]
@rashtao I think this is good to go! Thoughts?

**Comment by rashtao** [comment]
I can see 

- frozen
- frozenSet
- frozenMap

why not also frozenList ?
For the rest it's OK.

I am sorry for having changed the tab/spaces format, I will pay attention in the future...

Thanks a lot for everything!

**Comment by UnbounDev** [comment]
I wasn't able to find an example of a frozen list in the [documentation](http://docs.datastax.com/en/cql/3.1/cql/cql_using/cqlUseUDT.html); are we sure this is supported?

No worries - there is now a contributors doc so all devs know the project format guidelines :)

**Comment by rashtao** [comment]
Effectively the only doc about that is: http://docs.datastax.com/en/cql/3.1/cql/cql_reference/collection_type_r.html?scroll=reference_ds_exb_vg5_yj__using-frozen-in-collection

There are no explicit examples in the doc, but you cannot create an index on a collection field unless it is frozen. Eg:

```sql
create table my_table (  id list<text>,  text_field text,  PRIMARY KEY(id));
```

would result in the following error:

```sql
InvalidRequest: code=2200 [Invalid query] message="Invalid collection type for PRIMARY KEY component id"
```

But this will work:

```sql
create table my_table (  id frozen<list<text>>,  text_field text,  PRIMARY KEY(id));
```

**Comment by UnbounDev** [comment]
Got it; added the `frozenList` query modifier, usage is

```js
qb.createColumnFamily("columnFamily")
      .frozen("uudtTypeColumn", "myUUDT")
      .frozenList("anyTypeListColumn", "anyType");

// compiles => CREATE COLUMNFAMILY cassanKnexy.columnFamily ( anyTypeListColumn FROZEN <LIST <anyType>> ) ;
```

**Pull request merged**
