### PR TITLE
1.14.0

### PR DESCRIPTION
**Pull request by UnbounDev**

### CODE REVIEW

**Comment by hyebrown** [comment]
Not sure why I'm still getting notified on these... :(  Happy New Year Azuqua devs!

**Comment by UnbounDev** [comment]
Hey there @hyebrown! I think maybe your `hiram@azuqua.com` email is still associated to your github account?

**Comment by hyebrown** [comment]
Not that I can find (just my yahoo account).  More troubling I can see/access many azuqua repositories (though I do not appear to be a member of the azuqua org -- not listed as 1 of the 8 members). 

I wouldn't know any of this except I keep getting notifications to my yahoo email account.

Mild annoyance for me, potential security risk for Azuqua (I'm not a risk, but if I still have access who else still does that might be...).

**Comment by hyebrown** [comment]
Actually I may be misrepresenting.  I have a separate github account for my current org (Allen Institute) that I can access the same repositories in the azuqua org from (y'all have a stack of public ones now?)

**Comment by UnbounDev** [comment]
Yea there are a number of public repos (including this one), maybe you're
just still subscribed?

**Comment by hyebrown** [comment]
ugh - that's what it is.  I was automatically subscribed to every repo in the azuqua org.  There doesn't appear to be a way to unwatch en masse...

**Pull request merged**
